---
abstract: 'simple email creation with auto text and html multipart body'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Email-Simple-Markdown
provides:
  Email::Simple::Markdown:
    file: lib/Email/Simple/Markdown.pm
    version: v0.6.0
requires:
  Carp: '0'
  Email::Abstract: '0'
  Email::MIME: '0'
  Email::Simple: '0'
  List::Util: '0'
  Module::Runtime: '0'
  Moo: '0'
  Text::MultiMarkdown: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Email-Simple-Markdown/issues
  homepage: https://github.com/yanick/Email-Simple-Markdown
  repository: https://github.com/yanick/Email-Simple-Markdown.git
version: 0.6.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Alessandro Ranellucci <aar@cpan.org>'
  - 'Gavin Carr <gavin@openfusion.com.au>'
